services:
  user-db:
    image: postgres:18-alpine
    container_name: laba-main-db-container
    environment:
      - POSTGRES_USER=laba_admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=laba_main_db
      - PGPORT=5432
    ports:
      - "5432:5432"
    volumes:
      - main-db-data:/var/lib/postgresql/data
    restart: unless-stopped
  auth-db:
    image: valkey/valkey:latest
    container_name: laba-auth-db-container
    ports:
      - "6379:6379"
    volumes:
      - auth-db-data:/data
    command: valkey-server --appendonly yes --requirepass "12345"
    restart: unless-stopped
  s3-db:
    image: minio/minio:latest
    container_name: laba-s3-db-container
    environment:
      - MINIO_ROOT_USER=laba_admin
      - MINIO_ROOT_PASSWORD=12345
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3-db-data:/data
    restart: unless-stopped
volumes:
  main-db-data:
  auth-db-data:
  s3-db-data:
