services:
  user-db:
    image: postgres:18-alpine
    container_name: laba-main-db-container
    environment:
      - POSTGRES_USER=laba_admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=laba_main_db
      - PGPORT=5432
    ports:
      - "5432:5432"
    volumes:
      - main-db-data:/var/lib/postgresql/data
    restart: unless-stopped
  auth-db:
    image: valkey/valkey:8.0-alpine
    container_name: laba-auth-db-container
    ports:
      - "6379:6379"
    volumes:
      - auth-db-data:/data
    command: valkey-server --appendonly yes --requirepass "12345"
    restart: unless-stopped
  s3-db:
    image: minio/minio:latest
    container_name: laba-s3-db-container
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    environment:
      - MINIO_ROOT_USER=laba_admin
      - MINIO_ROOT_PASSWORD=12345678
    volumes:
      - s3-db-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  main-db-data:
  auth-db-data:
  s3-db-data:
