general_params:
  env: dev
  secret_key: 36080001349340267925113477454910
  http_server_address: localhost:8080
main_db_params:
  db_username: laba_admin
  db_password: 12345
  db_name: laba_main_db
  db_port: 5432
  db_host: localhost
  db_timeout: 5
auth_db_params:
  db_host: localhost:6379
  db_username: laba_admin
  db_password: 12345
udp_params:
  udp_server_address: localhost
  port: 9090
s3_params:
  endpoint: localhost:9000
  access_key_id: laba_admin
  secret_access_key: 12345678
  use_ssl: false
  bucket_name: voice_messages
